[package]
name = "serde-systemd-unit"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.9.3"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
itertools = "0.14.0"

[lints]
workspace = true