name: End to End Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f43
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Clean up space
        run: |
          df -h
          # Wipe stuff in our host /usr to make some space

          # We don't need the android SDK
          rm -rf /hostusr/local/lib/android
          # We're a Rust shop, not a Haskell shop
          rm -rf /hostusr/local/.ghcup
          rm -rf /hostfs/opt/ghc
          # We don't even use .NET
          rm -rf /hostusr/share/dotnet
          # We don't need CodeQL in this action
          rm -rf /hostfs/opt/hostedtoolcache/CodeQL

          echo "After cleanup:"
          df -h

      - name: Install dependencies
        run: |
          dnf install -y isotovideo edk2-ovmf qemu
          dnf builddep -y ci/readymade.spec

      - name: Run tests
        run: cd test && ./test.sh
